viewer/basic_app/urls.py
from django.urls import path,re_path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name="basic_app"

urlpatterns=[
    path('searchbar/',views.searchbar,name='searchbar'),
    re_path(r'^faculties$',views.FacultyListView.as_view(),name="list"),
    re_path(r'^(?P<pk>\d+)/$',views.FacultyDetailView.as_view(),name='detail'),
    re_path(r'^create/$',views.FacultyCreateView.as_view(),name='create'),
    re_path(r'^update/(?P<pk>\d+)/$',views.FacultyUpdateView.as_view(),name='update'),
    re_path(r'^delete/(?P<pk>\d+)/$',views.FacultyDeleteView.as_view(),name='delete'),
    path('faculty_csv/',views.faculty_csv,name='faculty_csv'),

]

viewer/viewer/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import include
from basic_app import views

urlpatterns = [
    path('',views.home,name='home'),
    #path('login/',views.user_login,name='login'),
    re_path(r'^basic_app/',include(('basic_app.urls','basic_app'),namespace='basic_app')),
    re_path(r'^admin/', admin.site.urls),
]

viewer/basic_app/models.py
from django.db import models
from django.urls import reverse
import datetime
# Create your models here.
class Faculty(models.Model):
    name=models.CharField(max_length=256)
    age=models.PositiveIntegerField()
    designation=models.CharField(max_length=50)
    faculty_id=models.CharField(max_length=5,blank=True)

    photo = models.ImageField(upload_to='photos',default='default_pic.jpg')

    MALE="male"
    FEMALE="female"

    GENDER_CHOICE=[
    (MALE,"male"),
    (FEMALE,"female")
    ]

    gender=models.CharField(
        max_length=10,
        choices=GENDER_CHOICE,
        default=MALE
    )

    dob=models.DateField(default=datetime.date.today)

    groups=[
    ("A+ve","A+ve"),
    ("B+ve","B+ve"),
    ("A-ve","A-ve"),
    ("B-ve","B-ve"),
    ("O+ve","O+ve"),
    ("AB-ve","AB-ve")
    ]

    blood_group=models.CharField(
        max_length=5,
        choices=groups,
        blank=True
    )


    aadhar_no=models.CharField(max_length=12)
    pan_no=models.CharField(max_length=10,blank=True)
    mobile=models.CharField(max_length=10,blank=True)
    email=models.EmailField(blank=True)


    state_choices = [
        ("Andhra Pradesh","Andhra Pradesh"),("Arunachal Pradesh ","Arunachal Pradesh "),("Assam","Assam"),("Bihar","Bihar"),("Chhattisgarh","Chhattisgarh"),
        ("Goa","Goa"),("Gujarat","Gujarat"),("Haryana","Haryana"),("Himachal Pradesh","Himachal Pradesh"),("Jammu and Kashmir ","Jammu and Kashmir "),
        ("Jharkhand","Jharkhand"),("Karnataka","Karnataka"),("Kerala","Kerala"),("Madhya Pradesh","Madhya Pradesh"),("Maharashtra","Maharashtra"),
        ("Manipur","Manipur"),("Meghalaya","Meghalaya"),("Mizoram","Mizoram"),("Nagaland","Nagaland"),("Odisha","Odisha"),("Punjab","Punjab"),("Rajasthan","Rajasthan"),
        ("Sikkim","Sikkim"),("Tamil Nadu","Tamil Nadu"),("Telangana","Telangana"),("Tripura","Tripura"),("Uttar Pradesh","Uttar Pradesh"),("Uttarakhand","Uttarakhand"),
        ("West Bengal","West Bengal"),("Andaman and Nicobar Islands","Andaman and Nicobar Islands"),("Chandigarh","Chandigarh"),
        ("Dadra and Nagar Haveli","Dadra and Nagar Haveli"),("Daman and Diu","Daman and Diu"),("Lakshadweep","Lakshadweep"),
        ("National Capital Territory of Delhi","National Capital Territory of Delhi"),("Puducherry","Puducherry")
        ]
    state=models.CharField(
    max_length=35,
    choices=state_choices,
    blank=True
    )
    district=models.CharField(max_length=256,blank=True)
    house_no=models.PositiveIntegerField(default=0)
    locality=models.CharField(default="unspecified",max_length=100)
    pin=models.CharField(max_length=6,blank=True)
    permanent_address_is_same_as_current_address=models.BooleanField(default=True)


    qualification_choices=[
    ("SSC","SSC"),
    ("Inter","Inter"),
    ("UG","UG"),
    ("PG","PG"),
    ("Phd","Phd"),
    ("Others","Others")
    ]
    qualification=models.CharField(
    max_length=25,
    choices=qualification_choices,
    blank=True
    )
    college=models.CharField(max_length=100,blank=True)
    graduation_year=models.CharField(max_length=4,blank=True)
    university=models.CharField(max_length=60,blank=True)
    percentage=models.DecimalField(decimal_places=2,max_digits=5,default=0.00)

    award=models.CharField(max_length=100,blank=True)
    year_of_award=models.CharField(max_length=4,blank=True)
    organisation_of_award=models.CharField(max_length=50,blank=True)

    #journals
    publication_journal_name=models.CharField(max_length=100,blank=True)
    publication_journal_vol=models.PositiveIntegerField(default=1)
    issn_no=models.PositiveIntegerField(default=0)
    publisher=models.CharField(max_length=100,blank=True)
    year_of_publication=models.CharField(max_length=4,blank=True)
    article_title=models.CharField(max_length=50,blank=True)




    #r&d
    project_title=models.CharField(max_length=100,blank=True)
    duration=models.PositiveIntegerField(default=1)
    cost_of_project=models.DecimalField(decimal_places=5,max_digits=10,default=0.00)
    funding_agency=models.CharField(max_length=100,blank=True)
    start_date=models.DateField(default=datetime.date.today)
    end_date=models.DateField(default=datetime.date.today)



    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={'pk' :self.pk})

    def __str__(self):
        return self.name

viewer/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from . import models
from django.urls import reverse_lazy

from django.http import FileResponse
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter

import csv
from django.http import HttpResponse
# Create your views here.

class FacultyListView(ListView):
    model=models.Faculty

class FacultyDetailView(DetailView):
    model=models.Faculty
    template_name='basic_app/faculty.html'

class FacultyCreateView(CreateView):
    fields=('name','age','designation','gender','dob','faculty_id','blood_group','aadhar_no',
    'pan_no','mobile','email','state','district','pin','house_no','locality','permanent_address_is_same_as_current_address',
    'qualification','college','university','percentage','award','year_of_award','organisation_of_award',
    'publication_journal_name','publication_journal_vol','issn_no','publisher','year_of_publication','article_title',
    'project_title','duration','cost_of_project','funding_agency','start_date','end_date'
    )
    model=models.Faculty

class FacultyUpdateView(UpdateView):
    fields=('name','age','designation','gender','dob','faculty_id','blood_group','aadhar_no',
    'pan_no','mobile','email','state','district','pin','house_no','locality','permanent_address_is_same_as_current_address',
    'qualification','college','university','percentage','award','year_of_award','organisation_of_award',
    'publication_journal_name','publication_journal_vol','issn_no','publisher','year_of_publication','article_title',
    'project_title','duration','cost_of_project','funding_agency','start_date','end_date'
    )
    model=models.Faculty

class FacultyDeleteView(DeleteView):
    model=models.Faculty
    success_url=reverse_lazy('basic_app:list')



def searchbar(request):
    if request.method=='GET':
        search=request.GET.get('search')


        facs=models.Faculty.objects.all().filter(faculty_id=search)

        return render(request,'basic_app/searchbar.html',{'facs':facs})


'''def venue_pdf(request):
    buf=io.BytesIO()

    c=canvas.Canvas(buf,pagesize=letter,bottomup=0)

    textob=c.beginText()
    textob.setTextOrigin(inch,inch)
    textob.setFont("Helvetica",14)

    lines=[]

    faculties=models.Faculty.objects.all()

    for faculty in faculties:
        lines.append(faculty.faculty_id)
        lines.append("Name:" + faculty.name)
        lines.append("Designation:" + faculty.designation)
        lines.append('--')


    for line in lines:
        textob.textLine(line)

    c.drawText(textob)
    c.showPage()
    c.save()
    buf.seek(0)

    return FileResponse(buf,as_attachment=True,filename='faculty_report.pdf')'''


def faculty_csv(request):
    response=HttpResponse(content_type='text/csv')
    response['Content-Disposition']='attachment;filename=faculty.csv'

    writer=csv.writer(response)

    faculties=models.Faculty.objects.all()

    writer.writerow(['Name','ID','Designation','Age','Gender','Email','Mobile Number','DOB','Aadhar','PAN','State','District','PIN','House Number','Locality','Qualification','College',
                    'University','Percentage','Award','Year of Award','Organisation of Award','Publication Journal','Journal Volume','ISSN Number','Publisher','Year of Publication',
                    'Article Title','Project Title','Duration','Cost of Project','Funding Agency','Start Date','End Date'])



    for faculty in faculties:
        writer.writerow([faculty.name,faculty.faculty_id,faculty.designation,faculty.age,faculty.gender,faculty.email,faculty.mobile,faculty.dob,faculty.aadhar_no,
                        faculty.pan_no,faculty.state,faculty.district,faculty.pin,faculty.house_no,faculty.locality,faculty.qualification,faculty.college,faculty.university,
                        faculty.percentage,faculty.award,faculty.year_of_award,faculty.organisation_of_award,faculty.publication_journal_name,faculty.publication_journal_vol,
                        faculty.issn_no,faculty.publisher,faculty.year_of_publication,faculty.article_title,faculty.project_title,faculty.duration,faculty.cost_of_project,
                        faculty.funding_agency,faculty.start_date,faculty.end_date])

    return response


def home(request):
    return render(request,'basic_app/home.html')


'''def user_login (request):
    if request.method == 'POST' :
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login (request, user)
                return render(request,'basic_app/faculties.html')
            else:
                return HttpResponse('user not active')
        else:
            return HttpResponse('User doesnt exist')
    else:
        return render(request,'login.html')'''


'''fields=('name','age','designation','gender','dob','faculty_id','blood_group','aadhar_no',
'pan_no','mobile','email','state','district','pin','house_no','locality','permanent_address_is_same_as_current_address',
'qualification','college','university','percentage','award','year_of_award','organisation_of_award',
'publication_journal_name','publication_journal_vol','issn_no','publisher','year_of_publication','article_title',
'project_title','duration','cost_of_project','funding_agency','start_date','end_date'
)'''

viewer/basic_app/templates/basic_app/faculty.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
          <link href="https://fonts.googleapis.com/css2?family=Merriweather&family=Montserrat&family=Sacramento&display=swap" rel="stylesheet">
      <style media="screen">
        a{
          text-decoration: none;
          padding-left: 50px;
        }

        .container123{
          margin: 10px;
        }

        body{
          color: #40514E;
          font-weight: normal;
          font-family: "Merriweather", sans-serif;
          margin: 0;
          text-align: center;
        }

        .head{
          display: inline;

          font-weight: bold;
          color: black;

        }

        h1{
          text-align: center;
          font-size: 50px;
          color: #035397;
          padding: 20px;
          font-family: "Merriweather", sans-serif;
        }

        h2{
          padding-bottom: 30px;
          font-family: "Montserrat", sans-serif;
          color: #11999E;
          font-weight: normal;
          text-align: center;
          padding-top: 10px;
        }
        h3{
          font-family: "Montserrat",
        }



        hr{
          border: dotted grey 6px;
          border-bottom: none;
          width: 6%;
          margin: 20px auto;
        }

        a:hover{
          color: white;
        }


        p{
          padding-left: 100px;
          margin-left:100px;
          text-align: center;
        }

        .btn{
          color:white;
          text-align: center;

        }

        a{
          color: white;
        }

        .hono{
          position: relative;
        }

        .btn-primary{
          display: inline-block;
          position: absolute;
          right:450px;
          top: 30px;
          width: 120px;
          padding: 10px 0;
          text-align: justify;
        }

        .btn-warning{
          display: inline-block;
          position:absolute;
          top: 30px;
          right:200px;
          width: 150px;
          padding: 10px 0;
          text-align: justify;
        }

        .btn-danger{
          position: absolute;
          top :30px;
          left:500px;
          width: 150px;
          padding: 10px 0;
          text-align: justify;
        }



      </style>
  </head>
  <body class="container123">
    <h1>Faculty Details</h1>
    <hr>
    <div class="top-container">
      <h2>Personal Details</h2>
    </div>
    <hr>
    <p>
      <div class="head">
        ID:
      </div>{{faculty.faculty_id}}</p>
    <p><div class="head">
        Name:
    </div>
    {{faculty.name}}</p>
    <p><div class="head">
        Age:
    </div>
    {{faculty.age}}</p>
    <p>
      <div class="head">
        Designation:
      </div>{{faculty.designation}}</p>
    <p><div class="head">
      Gender:
    </div>{{faculty.gender}}</p>
    <p><div class="head">
      Date of Birth:
    </div> {{faculty.dob}}</p>
    <p><div class="head">
      Blood Group:
    </div>{{faculty.blood_group}}</p>
    <p><div class="head">
      Aadhar:
    </div>{{faculty.aadhar_no}}</p>
    <p><div class="head">
      PAN:
    </div>{{faculty.pan_no}}</p>

    <div class="top-container">
      <h2>Contact Details</h2>
    </div>
    <hr>
    <p><div class="head">
      Mobile:
    </div>{{faculty.mobile}}</p>
    <p><div class="head">
      Email:
    </div>{{faculty.email}}</p>
    <br>

    <div class="top-container">
      <h2>Education Details</h2>
    </div>
    <hr>
    <p><div class="head">
      Qualification:
    </div>{{faculty.qualification}}</p>
    <p><div class="head">
      College:
    </div>{{faculty.college}}</p>
    <p><div class="head">
      University:
    </div>{{faculty.university}}</p>
    <p><div class="head">
      Percentage:
    </div>{{faculty.percentage}}</p>
    <p><div class="head">
      Year of Graduation:
    </div>{{faculty.graduation_year}}</p>

    <div class="top-container">
      <h2>Research</h2>
    </div>
    <hr>
    <p><div class="head">
      Project Title:
    </div>{{faculty.project_title}}</p>
    <p><div class="head">
      Duration:
    </div>{{faculty.duration}}</p>
    <p><div class="head">
      Cost:
    </div>{{faculty.cost_of_project}}</p>
    <p><div class="head">
      Funding Agency:
    </div>{{faculty.funding_agency}}</p>
    <p><div class="head">
      Start Date:
    </div>{{faculty.start_date}}</p>
    <p><div class="head">
      End Date:
    </div>{{faculty.end_date}}</p>

    <div class="top-container">
      <h2>Address</h2>
    </div>
    <hr>
    <p><div class="head">
      State:
    </div>{{faculty.state}}</p>
    <p><div class="head">
      District:
    </div>{{faculty.district}}</p>
    <p><div class="head">
      PIN:
    </div>{{faculty.pin}}</p>
    <p><div class="head">
      House Number:
    </div>{{faculty.house_no}}</p>
    <p><div class="head hono">
      Locality:
    {{faculty.locality}}</p>




    <button  class="btn btn-primary" type="button" name="button"><a href="{% url 'basic_app:list' %}">Back</a></button>
    <br>
    <button type="button" name="button" class="btn btn-warning"><a href="{% url 'basic_app:update' pk=faculty.pk%}">Update</a></button>
    <br>
    <button type="button" name="button" class="btn btn-danger"><a href="{% url 'basic_app:delete' pk=faculty.pk%}">Delete</a></button>
  </div>
  </body>

</html>


<!--fields=('name','age','designation','gender','dob','faculty_id','blood_group','aadhar_no',
  'pan_no','mobile','email','state','district','pin','permanentAddressSameAsCurrentAddress',
  'qualification','college','university','percentage','award','year_award','org_award',
  'journal_name','journal_vol','issn_no','publisher','year_of_publication','article_title',
  'project_title','duration','cost_of_project','funding_agency','start_date','end_date'
  )--!>

viewer/basic_app/templates/basic_app/faculty_confirm_delete.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
      <link href="https://fonts.googleapis.com/css2?family=Merriweather&family=Montserrat&family=Sacramento&display=swap" rel="stylesheet">
      <style media="screen">
        a{
          color: white;
          text-decoration: none;
        }

        body{
          text-align: center;
        }

        h1{
          font-size: 50px;
          color: #035397;
          padding: 20px;
          font-family: "Merriweather", sans-serif;
        }


      </style>
  </head>
  <body>
    <h1>Confirm the Deletion?</h1>
    <form method="post">
      {% csrf_token %}
    <button type="submit" name="button" class="btn btn-danger"><!--<input type="submit" name="" value="Delete">-->Delete</button>
      <button type="button" name="button" class="btn btn-primary"> <a href="{% url 'basic_app:detail' pk=faculty.pk %}">Cancel</a></button>

    </form>
  </body>
</html>

viewer/basic_app/templates/basic_app/faculty_form.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <center>
  <body>
    <h1>
      {% if not form.instance.pk %}
      Create New Entry
      {% else %}
      Update Entry
      {% endif %}
    </h1>
    <br>

    <form  method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" name="" value="submit">
    </form>
  </body>
</center>
</html>

viewer/basic_app/templates/basic_app/faculty_list.html
<!DOCTYPE html>
{%load static%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather&family=Montserrat&family=Sacramento&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <style media="screen">
    #search2{
        position: absolute;
        right:5px;
        top:10px;
    }

    #search1{
        position: absolute;
        right:80px;
        width:15%;
        top: 10px;
    }

    #navparent{
        position: relative;
    }

    .faculty-list{
      margin: 20px;
    }

    .faculty-name{

      padding: 0px;
      margin:0px;
      margin-top: 10px;
      background-color: #D6E4E5;
      margin: 0px;
      padding: 7px;
      margin:5px;
      border-radius: 5px;
    }

    a{
      text-decoration: none;
    }

    h1{
      margin-top:20px;
      text-align: center;
      padding: 20px;
      font-size: 50px;
      color:#035397;
      font-family: "Merriweather", sans-serif;
    }

    hr{
      border: dotted grey 6px;
      border-bottom: none;
      width:6%;
      margin: 20px auto;
      margin-bottom: 10px;
    }

    h3{
      font-family: "Montserrat", sans-serif;
      color: #11999E;
      font-weight: bold;
      padding-left: 8px;

    }

    .brand{
      font-weight: bold;
      font-size:1.5rem;
    }

    #report{
      font-size:1.25rem;
    }

    #add{
      color: white;
    }

    .btn{
      text-align: center;
      align-items: center;
      margin-left: 54px;
    }

  </style>
  </head>
  <body >
    <!--<form action="{% url 'basic_app:searchbar' %}" method="get">
        {% csrf_token %}
        <input type="text" name="search" id="search1">
        <button type="submit" name="submit" id="search2">Search</button>
      </form>-->
      <form action="{% url 'basic_app:searchbar' %}" method="get">
        {% csrf_token %}
        <nav class="navbar navbar-expand-lg bg-light">
          <div class="container-fluid">
            <a class="navbar-brand brand" href="#">Faculty Management System</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'basic_app:faculty_csv'%}" id="report">Generate Report</a>
                </li>
            </div>
              <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Enter Faculty ID" aria-label="Search" type="text" name="search" id="search1" required>
                <button class="btn btn-outline-success" type="submit" id="search2" name="submit" >Search</button>
              </form>
            </div>
          </div>
      </nav>
      </form>

    <h1>Faculty List</h1>
    <hr>
    <ul class="faculty-list" style="list-style-type: none;">
      {% for faculty in faculty_list %}
      <div class="faculty-name">
        <h3 class><li><a href="{{faculty.id}}">{{faculty.name}}</a></li></h3>
      </div>
      {% endfor %}
    </ul>
    <center> <button type="button" name="button" class="btn btn-primary"><a href="{% url 'basic_app:create' %}" id="add">Add New Faculty</a></button></center>
  </body>
</html>

<!--<form action="{% url 'basic_app:searchbar' %}" method="get">
    {% csrf_token %}
    <input type="text" name="search" id="search1">
    <button type="submit" name="submit" id="search2">Search</button>
  </form>-->



<!--
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="home.css">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light" id="navparent">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Faculty Management</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" id="search1">
              <button class="btn btn-outline-success" type="submit" id="search2">Search</button>
            </form>
          </div>
        </div>
      </nav>

</body>
</html>
--!>

viewer/basic_app/templates/basic_app/hello.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Hello</title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
      <link href="https://fonts.googleapis.com/css2?family=Merriweather&family=Montserrat&family=Sacramento&display=swap" rel="stylesheet">
      <style media="screen">
      h1{
        text-align: center;
        font-size: 50px;
        color: #035397;
        padding: 20px;
        font-family: "Merriweather", sans-serif;
      }
      </style>
  </head>
  <body>
    <h1>Hello World!</h1>
    <h1>My name is {{name}}</h1>
  </body>
</html>

viewer/basic_app/templates/basic_app/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather&family=Montserrat&family=Sacramento&display=swap" rel="stylesheet">
    <style media="screen">
    h1{
      text-align: center;
      font-size: 50px;
      color: #035397;
      padding: 20px;
      font-family: "Merriweather", sans-serif;
    }
    body{
      text-align: center;
      align-items: center;
    }
    a{
      text-decoration: none;
      text-align: center;
    }
    a:hover{
      color: blue;
    }
    </style>

  </head>
  <body>
    <h1>Welcome to the  website!</h1>
    <p>This is a demo working model of Faculty Management System developed using Django and able to implement basic CRUD operations.</p>
    <h2><a href="{% url 'basic_app:list' %}">Go to Website</a></h2>

  </body>
</html>

viewer/basic_app/templates/basic_app/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form action="{% url 'basic_app:login' %}" method="post">
      <label for="username">Username</label>
      <input type="text" name="username" value="">
      <label for="password">Username</label>
      <input type="password" name="password" value="">
      <input type="submit" name="login" value="Login">

    </form>
  </body>
</html>

viewer/basic_app/templates/basic_app/searchbar.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
      <link href="https://fonts.googleapis.com/css2?family=Merriweather&family=Montserrat&family=Sacramento&display=swap" rel="stylesheet">
      <style media="screen">
        h1{
          text-align: center;
          font-size: 50px;
          color: #035397;
          padding: 20px;
          font-family: "Merriweather", sans-serif;
        }
        a{
          text-decoration: none;
          color: white;
        }
        a:hover{
          color: white;
        }
        btn:hover{
          color:#00081;
        }
        #results{
          color:black;
        }
        #results:hover{
          color: blue;
        }
        ul{
          list-style:none;
        }
      </style>
  </head>
  <body style="text-align:center">

    {% if facs %}
    <h1>Results Found!</h1>
    <br>
    <ul>
      {% for i in facs%}
      <li><h2><a href="/basic_app/{{i.id}}" id="results">{{i.name}}</a></h2></li>
      {% endfor %}
    </ul>

    {% else %}
    <h1>No results!</h1>
    <button type="button" name="button" class="btn btn-primary"><a href="{% url 'basic_app:list' %}">Go back to list</a></button>

    {% endif %}

  </body>
</html>